### ISSUE TITLE
新的题目【高仿摆摊骗术】

### ISSUE THREAD

**Issue by xkrato** [buchijiang/QQSG#4]
题目
【高仿摆摊骗术】骗子往往使用相近的名字进行诈骗，例如：“骗子1” 和 “骗子l”，看上去相似，其实一个是数字1，一个是字母L的小写，遇到这种情况，我们应该：

答案
查看交易时物品和等级是否正确

**Comment by xkrato** [comment]
![1704466175634](https://github.com/buchijiang/QQSG/assets/77837717/acce8220-6198-4c78-876d-4e1dd37867c7)

**Comment by xkrato** [comment]
![1704466175634](https://github.com/buchijiang/QQSG/assets/77837717/69f3ffbc-57bf-4e0c-b4c5-591a82ce089d)

**Comment by liuhusk** [comment]
收到

**Comment by xkrato** [comment]
![new_quest](https://github.com/buchijiang/QQSG/assets/77837717/e20cca98-0dbe-4a34-ad01-713974cf7598)

**Comment by buchijiang** [comment]
收到
